server:
  port: 9094

#knife4j配置
knife4j:
  # 是否是生产环境
  production: false

spring:

  # mysql 配置
  datasource:
    url: jdbc:mysql://localhost:3306/interaction_engine_v2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

  # redis 缓存配置
  redis:
    host: localhost
    port: 6379
    database: 10

url:
  ip:
    # 权限收放引擎IP
    permControlEngineIp: 10.20.54.133
  port:
    # 权限收放引擎端口
    permControlEnginePort: 9004
  path:
    # 用户的上级用户信息
    superiorUserByUser: /api/getSysUserMangerByUserIdOrUserName
    # 总经理用户信息
    bigBossUser: /api/getGeneralManagerSysUser
    # 部门信息
    departments: /api/getSysDepartmentList
    # 部门负责人用户信息
    departmentHeadByDepartmentId: /api/getSysUserManagerByDepartmentId/{departmentId}
    # 用户信息
    userInfoByName: /api/queryByUserName/{userName}



















